"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class robot_state_control_lcmt(object):
    __slots__ = ["q", "v", "tau"]

    __typenames__ = ["float", "float", "float"]

    __dimensions__ = [[19], [18], [12]]

    def __init__(self):
        self.q = [ 0.0 for dim0 in range(19) ]
        self.v = [ 0.0 for dim0 in range(18) ]
        self.tau = [ 0.0 for dim0 in range(12) ]

    def encode(self):
        buf = BytesIO()
        buf.write(robot_state_control_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>19f', *self.q[:19]))
        buf.write(struct.pack('>18f', *self.v[:18]))
        buf.write(struct.pack('>12f', *self.tau[:12]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_state_control_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_state_control_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = robot_state_control_lcmt()
        self.q = struct.unpack('>19f', buf.read(76))
        self.v = struct.unpack('>18f', buf.read(72))
        self.tau = struct.unpack('>12f', buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if robot_state_control_lcmt in parents: return 0
        tmphash = (0xbe14089c923ad667) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if robot_state_control_lcmt._packed_fingerprint is None:
            robot_state_control_lcmt._packed_fingerprint = struct.pack(">Q", robot_state_control_lcmt._get_hash_recursive([]))
        return robot_state_control_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

